services:
  python-chess:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: python-chess-container
    stdin_open: true
    tty: true
    volumes:
        - "./src:/app/src"
        - "./chess-games.pgn.zst:/data/chess-games.pgn.zst"

  mongodb:
    image: mongo:8.0
    container_name: chess-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - chess-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

volumes:
  chess-mongo-data:
