services:
  python-chess:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: python-chess-container
    stdin_open: true
    tty: true
    volumes:
        - "./chess-games.pgn.zst:/data/chess-games.pgn.zst"
